### PR TITLE
fix single argument expansion for builtins (fixes #301)

### LINKED ISSUE #301: fixedbugs/issue5793.go: Compiler panic due to index out of range.
This is the [third](https://github.com/gopherjs/gopherjs/blob/67b6a9773dd8e6c85f7c56124e9ac110d6999f32/tests/run.go#L48-L54) of four panics found via Go compiler tests added in #296.

This is the failing test case:

```Go
// Issue 5793: calling 2-arg builtin with multiple-result f() call expression gives
// spurious error.

package main

func complexArgs() (float64, float64) {
	return 5, 7
}

func appendArgs() ([]string, string) {
	return []string{"foo"}, "bar"
}

func appendMultiArgs() ([]byte, byte, byte) {
	return []byte{'a', 'b'}, '1', '2'
}

func main() {
	if c := complex(complexArgs()); c != 5+7i {
		panic(c)
	}

	if s := append(appendArgs()); len(s) != 2 || s[0] != "foo" || s[1] != "bar" {
		panic(s)
	}

	if b := append(appendMultiArgs()); len(b) != 4 || b[0] != 'a' || b[1] != 'b' || b[2] != '1' || b[3] != '2' {
		panic(b)
	}
}
```

It causes a panic in `github.com/gopherjs/gopherjs/compiler` package, `(*funcContext) translateBuiltin` method, in [`compiler/expressions.go:882`](https://github.com/gopherjs/gopherjs/blob/67b6a9773dd8e6c85f7c56124e9ac110d6999f32/compiler/expressions.go#L882). The relevant code:

```Go
case "complex":
	return c.formatExpr("new %s(%e, %e)", c.typeName(typ), args[0], args[1])
```

The panic occurs because there's only one argument to complex, it's a func that has 2 return arguments. So doing `args[1]` causes an index out of range panic:

```
panic: runtime error: index out of range
```

The fix is to handle this situation correctly.

I have thought about how to fix it, but it's not immediately obvious to me because I am not yet familiar with the relevant code and approach. @neelance, your expertise here would be very helpful.

#### Reproduce

```bash
$ cd $GOPATH/src/github.com/gopherjs/gopherjs/tests
$ go run run.go -v -summary -show_known_fails -- fixedbugs/issue5793.go
goos: "darwin", goarch: "js"
# go run run.go -show_known_fails -- fixedbugs/issue5793.go
exit status 2
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateBuiltin(0xc8200e5970, 0x6339f0, 0x7, 0xc82012c5c0, 0x1, 0x1, 0xc82012d900, 0xcb46b0, 0x909820, 0xc82012d9f0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/expressions.go:882 +0x41c7
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc8200e5970, 0xcb5078, 0xc820132200, 0x909820)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/expressions.go:547 +0x11eee
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateImplicitConversion(0xc8200e5970, 0xcb5078, 0xc820132200, 0xcb46b0, 0x909820, 0x6)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1085 +0x291
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateAssignOfExpr(0xc8200e5970, 0xcb4f28, 0xc820134000, 0xcb5078, 0xc820132200, 0xcb46b0, 0x909820, 0xc820153701, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/statements.go:731 +0xdda
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc8200e5970, 0xcb50b0, 0xc820132240, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/statements.go:348 +0xd76f
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc8200e5970, 0xcb5158, 0xc8201322c0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/statements.go:41 +0x10c28
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc8200e5970, 0xc820132600, 0x3, 0x4)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0x9e
github.com/gopherjs/gopherjs/compiler.translateFunction.func1()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:679 +0x9ba
github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc8200e5970, 0x1, 0xc820157820, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/utils.go:64 +0x84
github.com/gopherjs/gopherjs/compiler.translateFunction(0xc820134560, 0x0, 0x0, 0x0, 0xc820129c20, 0xc8200e5550, 0xc820129ec0, 0xc820019140, 0xc82012c530, 0x4, ...)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:680 +0x6d0
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction.func1(0xc82012c530, 0x4, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:562 +0x90a
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction(0xc8200e5550, 0xc820129c50, 0xc820019140, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:571 +0x3e2
github.com/gopherjs/gopherjs/compiler.Compile.func9()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:340 +0x42
github.com/gopherjs/gopherjs/compiler.Compile.func5(0xc8201433b0, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:230 +0xa6
github.com/gopherjs/gopherjs/compiler.Compile(0x6358d8, 0x4, 0xc820030168, 0x1, 0x1, 0xc820013c80, 0xc82012c0c0, 0x0, 0x22723292, 0x0, ...)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:341 +0x47ec
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc82000f8e0, 0xc8201269b0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/build/build.go:466 +0xfbf
github.com/gopherjs/gopherjs/build.(*Session).BuildFiles(0xc82000f8e0, 0xc82012c060, 0x1, 0x1, 0xc820126910, 0x47, 0xc82000f660, 0x12, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/build/build.go:341 +0x2c9
main.main.func3.1(0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:235 +0x473
main.handleError(0xc820159b40, 0xc820013c00, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:610 +0x46
main.main.func3(0xc82012a540, 0xc82012c060, 0x1, 0x1)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:242 +0x5c
github.com/spf13/cobra.(*Command).execute(0xc82012a540, 0xc820011ff0, 0x1, 0x1, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/github.com/spf13/cobra/command.go:499 +0x869
github.com/spf13/cobra.(*Command).Execute(0xc82012ac40, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/github.com/spf13/cobra/command.go:582 +0x46a
main.main()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:461 +0x13cd

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

knfl	fixedbugs/issue5793.go	0.019s
    1 knfl
```

### PR DESCRIPTION
**Pull request by neelance**

### CODE REVIEW

**Comment by neelance** [comment]
@shurcooL Please review.

File: compiler/prelude/prelude.go [hunk 1]
```diff
@@ -335,6 +335,10 @@ var $append = function(slice) {
 };
 
 var $appendSlice = function(slice, toAppend) {
+  if (toAppend.constructor === String) {
+    var bytes = $stringToBytes(toAppend);
+    return $internalAppend(slice, bytes, 0, bytes.length);
+  }
```
Comment (shurcooL) [inline compiler/prelude/prelude.go]: Question, why was this seemingly moved from Go code in `expressions.go` to here?

**Comment by shurcooL** [comment]
I asked one question above.

LGTM. Feel free to merge when it's ready from your side.

File: compiler/prelude/prelude.go (hunk 1 above)
Comment (neelance) [inline compiler/prelude/prelude.go]: Because this is a special case of `append`, so it fits better here. Before, `translateConversionToSlice` covered this case, but this is not used for `append` any more. Go Spec: `As a special case, append also accepts a first argument assignable to type []byte with a second argument of string type followed by .... This form appends the bytes of the string.`

Comment (shurcooL) [inline compiler/prelude/prelude.go]: Makes sense, thanks!
