### PR TITLE
Future-proof untyped nil handling.

### LINKED ISSUE #1011: Compiler panic at tip Go due to assumption about nil basic types
Gopherjs breaks at ~[CL 284052](https://golang.org/cl/284052)~ [CL 289715](https://golang.org/cl/289715) in the Go repository, due to an assumption about nil basic types here:
https://github.com/gopherjs/gopherjs/blob/bed99a852dfeb7c8aad4ac454357a198750247e1/compiler/expressions.go#L738
(`t.Kind()` is now `types.UntypedNil`)

This is reproducible as follows:
```
> GO111MODULE=off go test -v -run=TestGoRepositoryCompilerTests ./tests                                                                                         
=== RUN   TestGoRepositoryCompilerTests                                                                             
goos: "linux", goarch: "js"                                                                                         
ok      fixedbugs/bug000.go     0.254s                                                                              
ok      fixedbugs/bug002.go     0.190s                                                                                                                                                                                                  
ok      fixedbugs/bug003.go     0.186s                                                                              
ok      fixedbugs/bug004.go     0.176s                                                                                                                                                                                                  
ok      fixedbugs/bug005.go     0.178s                                                                              
# go run run.go -- fixedbugs/bug006.go                                                                                                                                                                                                  
exit status 2                                                                                                       
panic: unexpected basic type [recovered]                                                                            
        panic: unexpected basic type                                                                                
                                                                                                                    
goroutine 1 [running]:                                                                                              
go/types.(*Checker).handleBailout(0xc00024a000, 0xc0000eed00)                                                       
        /usr/local/google/home/rfindley/src/go2/src/go/types/check.go:245 +0x9f                                   
panic(0x918020, 0xa87510)                                                                                       
        /usr/local/google/home/rfindley/src/go2/src/runtime/panic.go:965 +0x1c7
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc00052c2c0, 0xa9a310, 0xc00071c1c0, 0xa9a310)
        /usr/local/google/home/rfindley/dev/go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:739 +0xf0d3
```

This appears to be a case of [Hyrum's law](https://www.hyrumslaw.com/) -- I'm not aware of documentation stating that a basic nil must be `types.UnsafePointer`, though please let me know if I've missed something.

Unless there is evidence that this implicit assumption about nil basic types is widespread, we'd like to land this change in `go/types` for go1.17.  It seems like a trivial fix, but I'm not familiar with the gopherjs compiler. Could someone take a look? Thanks.

CC @dmitshur

### PR DESCRIPTION
**Pull request by nevkontakte**
Upstream changes introduced in https://golang.org/cl/284052 introduced several new cases where `nil` identifier would be treated as untyped by `go/types` and an implicit type conversion would be expected. These changes future-proof GopherJS against this particular change.

I've also discovered an additional case, where untyped nil was causing a panic even with Go 1.16: `var _ *int = nil`, I fixed that as well.

I've manually tested these changes against Go `tip`: `go-tip install . && GOPHERJS_NO_VERSION_CHECK=true GOROOT="$(go-tip env GOROOT)" gopherjs test ./tests`.

This PR also includes a couple of changes that make debugging compiler panics and testing with unreleased versions a bit easier.

Fixes #1011.

### CODE REVIEW

File: compiler/package.go [hunk 1]
```diff
@@ -120,7 +120,20 @@ func (pi packageImporter) Import(path string) (*types.Package, error) {
 	return pi.importContext.Packages[a.ImportPath], nil
 }
 
-func Compile(importPath string, files []*ast.File, fileSet *token.FileSet, importContext *ImportContext, minify bool) (*Archive, error) {
+func Compile(importPath string, files []*ast.File, fileSet *token.FileSet, importContext *ImportContext, minify bool) (_ *Archive, comError error) {
```
Comment (dmitshur) [inline compiler/package.go:123]: Consider modifying `err := recover()` to `e := recover()` and renaming `comError` to `err`, since that might look cleaner. `comError` only makes sense in the context of the defer, otherwise it is just the error that Compile returns, so `err` is a simple and clear name.

File: compiler/statements.go [hunk 2]
```diff
@@ -22,6 +22,27 @@ func (fc *funcContext) translateStmtList(stmts []ast.Stmt) {
 }
 
 func (fc *funcContext) translateStmt(stmt ast.Stmt, label *types.Label) {
+	defer func() {
+		err := recover()
+		if err == nil {
+			return
+		}
+		if _, yes := bailingOut(err); yes {
```
Comment (dmitshur) [inline compiler/statements.go:30]: Consider also using `ok` instead of `yes` here, that's what most Go code does, making it more readable.

File: compiler/utils.go [hunk 3]
```diff
@@ -738,3 +740,55 @@ func (st signatureTypes) Param(i int, ellipsis bool) types.Type {
...
+
+// FatalError is an error compiler panics with when it encountered a fatal error.
+//
+// FatalError implements io.Writer, which can be used to record any free-form
+// debugging details for human consumption. This information will be included
+// into String() result along with the rest.
+type FatalError struct {
+	cause interface{}
+	stack []byte
+	clues bytes.Buffer
```
Comment (dmitshur) [inline compiler/utils.go:752]: Consider using `strings.Builder` here since it might be a better fit.

File: compiler/utils.go [hunk 4]
```diff
@@ -738,3 +740,55 @@ func (st signatureTypes) Param(i int, ellipsis bool) types.Type {
...
+		return errors.New(s)
+	}
+	return fmt.Errorf("[%T]: %v", b.cause, b.cause)
+}
+
+// Write implements io.Writer and can be used to store free-form debugging clues.
+func (b *FatalError) Write(p []byte) (n int, err error) { return b.clues.Write(p) }
+
+func (b FatalError) Error() string {
+	buf := &bytes.Buffer{}
```
Comment (dmitshur) [inline compiler/utils.go:772]: Similarly here.

File: compiler/version_check.go [hunk 5]
```diff
@@ -19,6 +21,9 @@ const GoVersion = 16
 // at goroot, and reports an error if it's not compatible
 // with this version of the GopherJS compiler.
```
Comment (dmitshur) [inline compiler/version_check.go:22]: Consider documenting the change to CheckGoVersion's behavior here.

Perhaps it's also worth including at https://github.com/gopherjs/gopherjs#environment-variables.

File: compiler/version_check.go [hunk 6]
```diff
@@ -19,6 +21,9 @@ const GoVersion = 16
...
 func CheckGoVersion(goroot string) error {
+	if nvc, err := strconv.ParseBool(os.Getenv("GOPHERJS_NO_VERSION_CHECK")); err == nil && nvc {
```
Comment (dmitshur) [inline compiler/version_check.go:24]: Maybe the name can be simplified to `GOPHERJS_VERSION_CHECK` to avoid the double negation? Since the error is being checked, it'll be fine when the env var is unset since `ParseBool` returns a non-nil error on the empty string. Another option is to use a non-negated verb like `GOPHERJS_SKIP_VERSION_CHECK`.

**Review by dmitshur — COMMENTED** [review]
Thanks for working on this.

I don't have a chance to look very closely at the compiler changes, but was able to leave optional style suggestions for you to consider in case they're helpful.

File: compiler/statements.go (hunk 2 above)
Comment (nevkontakte) [reply compiler/statements.go:30]: I am aware of this convention, but was reluctant to follow it because in this particular case the meaning of "ok" is unclear: is it ok when we are panicing or when we aren't? "Yes" answers the question more directly, so I settled on it.

File: compiler/utils.go (hunk 3 above)
Comment (nevkontakte) [reply compiler/utils.go]: Done.

File: compiler/utils.go (hunk 4 above)
Comment (nevkontakte) [reply compiler/utils.go]: Done.

File: compiler/version_check.go (hunk 6 above)
Comment (nevkontakte) [reply compiler/version_check.go]: Good point, I prefer `GOPHERJS_SKIP_VERSION_CHECK`, since it seems a bit more self-descriptive. I'm not much concerned about its length, since it should be only rarely needed by people working on GopherJS itself.

File: compiler/version_check.go (hunk 5 above)
Comment (nevkontakte) [reply compiler/version_check.go:22]: Good point, done. I'll also add it to the developer instructions in the wiki once the PR is merged.

**Review by flimzy — APPROVED** [review]
