### PR TITLE
syscalls: move away from deprecated CloneElementAt

### LINKED ISSUE #809: Failed to Run `node-gyp rebuild` Needed for `gopherjs test` on Linux
I'm having trouble running `gopherjs test` on my Linux box. It works fine on my Mac after going through the system call setup. https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md

### Failure output
```
> $ pwd
/home/norunners/poc/vert/src/github.com/gopherjs/gopherjs/node-syscall

> $ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.0.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/norunners/poc/vert/src/github.com/gopherjs/gopherjs/node-syscall/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/norunners/.node-gyp/10.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/norunners/.node-gyp/10.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/norunners/.node-gyp/10.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/norunners/poc/vert/src/github.com/gopherjs/gopherjs/node-syscall',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/norunners/poc/vert/src/github.com/gopherjs/gopherjs/node-syscall/build'
  CXX(target) Release/obj.target/syscall/syscall.o
../syscall.cc: In function ‘intptr_t toNative(v8::Local<v8::Value>)’:
../syscall.cc:28:35: error: ‘class v8::Array’ has no member named ‘CloneElementAt’
       native[i] = toNative(array->CloneElementAt(i));
                                   ^~~~~~~~~~~~~~
make: *** [syscall.target.mk:93: Release/obj.target/syscall/syscall.o] Error 1
make: Leaving directory '/home/norunners/poc/vert/src/github.com/gopherjs/gopherjs/node-syscall/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.16.4-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/norunners/poc/vert/src/github.com/gopherjs/gopherjs/node-syscall
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

### Test Failure:
```
> $ pwd
/home/norunners/poc/vert/src/github.com/norunners/vert

> $ gopherjs test
PASS
fatal error: all goroutines are asleep - deadlock!
FAIL	github.com/norunners/vert	0.790s
```

### Additional Info:
```
> $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/norunners/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/norunners/poc/vert"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build058352341=/tmp/go-build -gno-record-gcc-switches"

> $ which python
/usr/bin/python

> $ python --version
Python 2.7.14
```

### PR DESCRIPTION
**Pull request by myitcv**
We currently use [Node 6.2.2](https://github.com/gopherjs/gopherjs/blob/8dffc02ea1cb8398bb73f30424697c60fcf8d4c5/circle.yml#L3) in CI for our `gopherjs test` runs. 

Ever since the start of the Node 6.x series, `v8::Array::CloneElementAt` has been deprecated; here's an example from [our most recent `master` build](https://circleci.com/gh/gopherjs/gopherjs/1584):

```
make: Entering directory `/home/ubuntu/gopherjs/node-syscall/build'
  CXX(target) Release/obj.target/syscall/syscall.o
../syscall.cc: In function ‘intptr_t toNative(v8::Local<v8::Value>)’:
../syscall.cc:28:51: warning: ‘v8::Local<v8::Object> v8::Array::CloneElementAt(uint32_t)’ is deprecated (declared at /home/ubuntu/.node-gyp/6.2.2/include/node/v8.h:3009): Cloning is not supported. [-Wdeprecated-declarations]
       native[i] = toNative(array->CloneElementAt(i));
                                                   ^
```

Per #809, in Node 10.x they have finally removed this method and hence attempts to [follow the syscall steps](https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md#nodejs-on-linux-and-macos) fail with:

```
make: Entering directory '/home/norunners/poc/vert/src/github.com/gopherjs/gopherjs/node-syscall/build'
  CXX(target) Release/obj.target/syscall/syscall.o
../syscall.cc: In function ‘intptr_t toNative(v8::Local<v8::Value>)’:
../syscall.cc:28:35: error: ‘class v8::Array’ has no member named ‘CloneElementAt’
       native[i] = toNative(array->CloneElementAt(i));
                                   ^~~~~~~~~~~~~~
```

This PR therefore drops our usage of the deprecated method, instead preferring to use [`v8::Object::Clone()`](https://github.com/v8/v8/blob/a7e6b0ee42db7509a716ca8380255bee2f6a6341/src/api.cc#L5015) as required. 

My C++ skills are however sorely lacking... so perhaps @neelance can offer some thoughts here (given I assume he originated the code?)

We also bump to using Node 10.x in the CI which brings us up-to-date and helps to verify the fix (all the tests pass).

Fixes #809

### CODE REVIEW

**Comment by myitcv** [comment]
@neelance - would appreciate if you had a couple of minutes spare to look this over.

@shurcooL @hajimehoshi - this PR is also ready for review.

**Comment by hajimehoshi** [comment]
I'm not familiar with node details, so I'd like to defer to other reviewers on this :-)

File: node-syscall/syscall.cc [hunk 1]
```diff
@@ -25,7 +25,17 @@ intptr_t toNative(Local<Value> value) {
     Local<Array> array = Local<Array>::Cast(value);
     intptr_t* native = reinterpret_cast<intptr_t*>(malloc(array->Length() * sizeof(intptr_t))); // TODO memory leak
     for (uint32_t i = 0; i < array->Length(); i++) {
+#if (NODE_MODULE_VERSION >= NODE_6_0_MODULE_VERSION)
+      v8::Local<v8::Value> elem = array->Get(i);
```
Comment (shurcooL) [inline node-syscall/syscall.cc]: This file does `using namespace v8;` on top, and 4 lines above we have `Local<Array> array`, etc.

So I think it'd be better to be consistent and drop the namespace here as well:

```C++
Local<Value> elem = array->Get(i);
```

Similarly on another line below.

File: node-syscall/syscall.cc [hunk 2]
```diff
@@ -25,7 +25,17 @@ intptr_t toNative(Local<Value> value) {
     Local<Array> array = Local<Array>::Cast(value);
     intptr_t* native = reinterpret_cast<intptr_t*>(malloc(array->Length() * sizeof(intptr_t))); // TODO memory leak
     for (uint32_t i = 0; i < array->Length(); i++) {
+#if (NODE_MODULE_VERSION >= NODE_6_0_MODULE_VERSION)
```
Comment (shurcooL) [inline node-syscall/syscall.cc]: What's the difference between `NODE_MODULE_VERSION` (here) and `NODE_MAJOR_VERSION` (above, on line 10)? Is it better to use `NODE_MODULE_VERSION` here?

Comment (myitcv) [reply node-syscall/syscall.cc]: I honestly don't know; rather pattern matching when it comes to C++... I've switched to using `NODE_MAJOR_VERSION`

File: node-syscall/syscall.cc (hunk 1 above)
Comment (myitcv) [reply node-syscall/syscall.cc]: Fixed.

**Comment by myitcv** [comment]
> Does anyone know where the syscall.cc code comes from? Is there an "upstream" version of it? Knowing if that's the case could make reviewing this easier.

No, I don't, hence why I pinged @neelance in case he had a couple of minutes to review.

I've just pushed up a couple of fixes in response to your comments. Given the tests pass, which make fairly heavy use of this layer, I think we can be fairly confident the fix is "good enough".

**Comment by myitcv** [comment]
> Is it even necessary to do the Clone?

I'm really unsure; I would defer to you on that question 😄 

I've pushed up accaa71 in an attempt to see whether the clone is required or not, at least against the reference that is our CI test suite.

**Comment by neelance** [comment]
I honestly don't know without looking into it some more.

**Comment by shurcooL** [comment]
The diff I get locally after running `npm install` is:

```diff
diff --git a/package-lock.json b/package-lock.json
index ed79b7a..6118aad 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -21,8 +21,8 @@
       "integrity": "sha512-r+MU0rfv4L/0eeW3xZrd16t4NZfK8Ld4SWVglYBb7ez5uXFWHuVRs6xCTrf1yirs9a4j4Y27nn7SRfO6v67XsQ==",
       "dev": true,
       "requires": {
-        "commander": "2.13.0",
-        "source-map": "0.6.1"
+        "commander": "~2.13.0",
+        "source-map": "~0.6.1"
       }
     }
   }
```

**Comment by shurcooL** [comment]
I guess I'll go with `npm install --no-save` as a solution. We don't want `npm install` to be modifying dependencies in `package-lock.json` in CI.

**Comment by shurcooL** [comment]
Well, that didn't work, because Circle CI runs a second `npm install` without the `--no-save` option as part of its "inference commands":

image

**Comment by shurcooL** [comment]
Ended up going back to Node.js 10.0.0 which doesn't cause `package-lock.json` to get modified, it's the simplest solution for now. We'll deal with newer Node.js versions after first migrating off the deprecated Circle CI 1.0 (#766).
