### PR TITLE
Fix internalize case for Date into time.Time struct.

### LINKED ISSUE #287: Date to time.time causes Uncaught Error: cannot internalize time.Time
According to the docs (if I'm reading them correctly) I can expose a method to Javascript and call it using MakeWrapper. GopherJS will take care of the conversion for the arguments within the exposed methods. (http://godoc.org/github.com/gopherjs/gopherjs/js#MakeWrapper)

However I can't seem to get a date object converted in to time.Time 

```
package main

import "github.com/gopherjs/gopherjs/js"
import "time"

func main() {
	js.Global.Set("pet", map[string]interface{}{
		"New": New,
	})
}

type Pet struct {
	birthday time.Time
}

func New(date time.Time) *js.Object {
	return js.MakeWrapper(&Pet{date})
}

func (p *Pet) Birthday() time.Time {
	return p.birthday
}

func (p *Pet) SetBirthday(date time.Time) {
	p.birthday = date
}
```
Playground link: http://www.gopherjs.org/playground/#/JEcteZCXUP

When I call dog.New(new Date()) I get
Uncaught Error: cannot internalize time.Time

Am I missing something here?

### PR DESCRIPTION
**Pull request by shurcooL**
~~Don't merge, this PR is a WIP (more commits to be pushed) and in need of review.~~ Ready for review.

Add a failing test case, then fix #287.

### CODE REVIEW

**Comment by shurcooL** [comment]
As desired, commit 098b579 added a failing test case and it indeed [failed](https://circleci.com/gh/gopherjs/gopherjs/551) with:

```
--- FAIL: TestInternalizeDate (0.01s)
/tmp/test.592009139:4
return;}$goroutine.exit=true;}catch(err){$goroutine.exit=true;throw err;}final
                                                                    ^
Error: cannot internalize time.Time
    at $callDeferred (/tmp/test.592009139:4:27597)
    at $panic (/tmp/test.592009139:4:28221)
    at $b (/tmp/test.592009139:27:44660)
    at $callDeferred (/tmp/test.592009139:4:27768)
    at $panic (/tmp/test.592009139:4:28221)
    at $internalize (/tmp/test.592009139:4:39702)
    at v.$externalizeWrapper (/tmp/test.592009139:4:35661)
    at eval (eval at <anonymous> (/tmp/test.592009139:28:16346), <anonymous>:1:18)
    at eval (native)
    at $packages.github.com/gopherjs/gopherjs/js_test.AE [as F] (/tmp/test.592009139:28:16346)
    at $packages.testing.BN (/tmp/test.592009139:27:44958)
    at $goroutine (/tmp/test.592009139:4:28817)
    at $runScheduled [as _onTimeout] (/tmp/test.592009139:4:29579)
    at Timer.listOnTimeout (timers.js:119:15)
FAIL	github.com/gopherjs/gopherjs/js	0.503s
```

The next commit will contain a fix that should get the failing test case to pass.

File: compiler/prelude/jsmapping.go [hunk 1]
```diff
@@ -313,6 +313,13 @@ var $internalize = function(v, t, recv) {
     }
     return s;
   case $kindStruct:
+    if (v !== null && v !== undefined && v.constructor === Date) {
```
Comment (shurcooL) [inline compiler/prelude/jsmapping.go]: There's probably a better way to do this instead of `v !== null && v !== undefined`, isn't there?

I needed it to avoid:

- TypeError: Cannot read property 'constructor' of null
- TypeError: Cannot read property 'constructor' of undefined

Comment (neelance) [inline compiler/prelude/jsmapping.go]: You can do `!v`, but that matches a few more cases. I'd go with the solution you have.

Comment (shurcooL) [inline compiler/prelude/jsmapping.go]: > I'd go with the solution you have.

Sounds good.

**Comment by shurcooL** [comment]
Commit 3844adbd682c6886fb5541fd147161c04c04088a fixed the failing test case.

This PR is ready for full review now.

**Comment by neelance** [comment]
Please see my comment on #287.

**Comment by shurcooL** [comment]
I've resolved that. What else does this PR need to be merged?

**Comment by neelance** [comment]
LGTM
